name: PR validation

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pre-commit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi;

      - name: pre-commit
        run: |
          pre-commit run -a

      - name: pytest check
        run: |
          python -m pytest
